# Generated by Django 5.2 on 2025-04-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacao',
            new_name='Transaction',
        ),
    ]
